spring:
  application:
    name: paytogether

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      validation-query: SELECT 1
      max-idle-time: 30m

logging:
  level:
    org.springframework.r2dbc.core: debug