spring:
  application:
    name: paytogether

  r2dbc:
    url: r2dbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 1
      max-size: 1
      validation-query: SELECT 1
      max-idle-time: 30m

paytogether:
  feign:
    twelvedata:
      url: https://api.twelvedata.com
      api-key: ${TWELVE_DATA_API_KEY}

logging:
  level:
    org.springframework.r2dbc.core: debug