name: Update CloudFront IPs in EC2 Security Group

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정(UTC) → 한국시간 오전 9시
  workflow_dispatch:

jobs:
  update-sg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Security Group ID
        run: |
          if [[ ! $SECURITY_GROUP_ID =~ ^sg-[0-9a-fA-F]{8,17}$ ]]; then
            echo "❌ SECURITY_GROUP_ID is invalid: $SECURITY_GROUP_ID"
            exit 1
          else
            echo "✅ SECURITY_GROUP_ID is valid: $SECURITY_GROUP_ID"
          fi
        env:
          SECURITY_GROUP_ID: ${{ secrets.CLOUDFRONT_SG_ID }}

      - name: Fetch CloudFront IP ranges
        run: |
          curl -s https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips \
            -o cloudfront-ips.json
          echo "Downloaded CloudFront IP list"
          jq '.CLOUDFRONT_GLOBAL_IP_LIST, .CLOUDFRONT_REGIONAL_EDGE_IP_LIST' cloudfront-ips.json > merged-ips.json

      - name: Debug Security Group ID
        run: echo "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}"
        env:
          SECURITY_GROUP_ID: ${{ secrets.CLOUDFRONT_SG_ID }}
          
      - name: Update Security Group
        env:
          SECURITY_GROUP_ID: sg-01021b724ac30544f
        run: |
          echo "Adding new CloudFront IP rules..."
          jq -r '.[] | .[]' merged-ips.json | while read ip; do
            aws ec2 authorize-security-group-ingress \
              --group-id $SECURITY_GROUP_ID \
              --protocol tcp --port 443 \
              --cidr "$ip" || true
          done

          echo "✅ Security group updated successfully!"
