name: ci
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  bulid-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/paytogether-official/${{ env.IMAGE_NAME }}:latest
            ghcr.io/paytogether-official/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_SSH_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Pulling the latest paytogether image from GHCR"
            sudo docker-compose pull paytogether-app
            
            echo "Stopping and removing existing containers"
            sudo docker-compose down
            
            echo "Starting containers with updated image"
            sudo docker-compose up -d
            
            echo "Deployment completed. Current containers:"
            sudo docker-compose ps