name: ci
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  bulid-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ vars.ORGANIZATION_VAR }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ vars.ORGANIZATION_VAR }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_SSH_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: 22
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=8080")

            if [ ! -z "$CONTAINER_ID" ]; then
            sudo docker stop $CONTAINER_ID
            sudo docker rm $CONTAINER_ID
            fi
            
            sudo docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            sudo docker run --name ${{ env.IMAGE_NAME }}-${{ github.sha }} -d -p 8080:8080 --env-file=.env.paytogether ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest